# Ref: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "install phase"
  pre_build:
    commands:
      - echo "pre_build phase"
  build:
    commands:
      - echo "build phase"
  post_build:
    commands:
      - echo "post_build phase"